template: testify
dir: "{{.InterfaceDir}}/mocks"
pkgname: "mocks"
filename: "mock_{{.InterfaceName}}.go"
packages:
  github.com/irbgeo/irregular-verbs-tgbot/internal/bot:
    interfaces:
      Sender:
