// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/irbgeo/go-tgbot"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSender creates a new instance of MockSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSender {
	mock := &MockSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSender is an autogenerated mock type for the Sender type
type MockSender struct {
	mock.Mock
}

type MockSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSender) EXPECT() *MockSender_Expecter {
	return &MockSender_Expecter{mock: &_m.Mock}
}

// Answer provides a mock function for the type MockSender
func (_mock *MockSender) Answer(ctx context.Context, callbackID string) error {
	ret := _mock.Called(ctx, callbackID)

	if len(ret) == 0 {
		panic("no return value specified for Answer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, callbackID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSender_Answer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Answer'
type MockSender_Answer_Call struct {
	*mock.Call
}

// Answer is a helper method to define mock.On call
//   - ctx context.Context
//   - callbackID string
func (_e *MockSender_Expecter) Answer(ctx any, callbackID any) *MockSender_Answer_Call {
	return &MockSender_Answer_Call{Call: _e.mock.On("Answer", ctx, callbackID)}
}

func (_c *MockSender_Answer_Call) Run(run func(ctx context.Context, callbackID string)) *MockSender_Answer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSender_Answer_Call) Return(err error) *MockSender_Answer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSender_Answer_Call) RunAndReturn(run func(ctx context.Context, callbackID string) error) *MockSender_Answer_Call {
	_c.Call.Return(run)
	return _c
}

// AnswerText provides a mock function for the type MockSender
func (_mock *MockSender) AnswerText(ctx context.Context, callbackID string, text string) error {
	ret := _mock.Called(ctx, callbackID, text)

	if len(ret) == 0 {
		panic("no return value specified for AnswerText")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, callbackID, text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSender_AnswerText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnswerText'
type MockSender_AnswerText_Call struct {
	*mock.Call
}

// AnswerText is a helper method to define mock.On call
//   - ctx context.Context
//   - callbackID string
//   - text string
func (_e *MockSender_Expecter) AnswerText(ctx any, callbackID any, text any) *MockSender_AnswerText_Call {
	return &MockSender_AnswerText_Call{Call: _e.mock.On("AnswerText", ctx, callbackID, text)}
}

func (_c *MockSender_AnswerText_Call) Run(run func(ctx context.Context, callbackID string, text string)) *MockSender_AnswerText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSender_AnswerText_Call) Return(err error) *MockSender_AnswerText_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSender_AnswerText_Call) RunAndReturn(run func(ctx context.Context, callbackID string, text string) error) *MockSender_AnswerText_Call {
	_c.Call.Return(run)
	return _c
}

// Edit provides a mock function for the type MockSender
func (_mock *MockSender) Edit(ctx context.Context, chatID int64, messageID int64, text string, kb *tgbot.InlineKeyboardMarkup) error {
	ret := _mock.Called(ctx, chatID, messageID, text, kb)

	if len(ret) == 0 {
		panic("no return value specified for Edit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, string, *tgbot.InlineKeyboardMarkup) error); ok {
		r0 = returnFunc(ctx, chatID, messageID, text, kb)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSender_Edit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Edit'
type MockSender_Edit_Call struct {
	*mock.Call
}

// Edit is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - messageID int64
//   - text string
//   - kb *tgbot.InlineKeyboardMarkup
func (_e *MockSender_Expecter) Edit(ctx any, chatID any, messageID any, text any, kb any) *MockSender_Edit_Call {
	return &MockSender_Edit_Call{Call: _e.mock.On("Edit", ctx, chatID, messageID, text, kb)}
}

func (_c *MockSender_Edit_Call) Run(run func(ctx context.Context, chatID int64, messageID int64, text string, kb *tgbot.InlineKeyboardMarkup)) *MockSender_Edit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *tgbot.InlineKeyboardMarkup
		if args[4] != nil {
			arg4 = args[4].(*tgbot.InlineKeyboardMarkup)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockSender_Edit_Call) Return(err error) *MockSender_Edit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSender_Edit_Call) RunAndReturn(run func(ctx context.Context, chatID int64, messageID int64, text string, kb *tgbot.InlineKeyboardMarkup) error) *MockSender_Edit_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockSender
func (_mock *MockSender) Send(ctx context.Context, chatID int64, text string, kb *tgbot.InlineKeyboardMarkup) error {
	ret := _mock.Called(ctx, chatID, text, kb)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, *tgbot.InlineKeyboardMarkup) error); ok {
		r0 = returnFunc(ctx, chatID, text, kb)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - text string
//   - kb *tgbot.InlineKeyboardMarkup
func (_e *MockSender_Expecter) Send(ctx any, chatID any, text any, kb any) *MockSender_Send_Call {
	return &MockSender_Send_Call{Call: _e.mock.On("Send", ctx, chatID, text, kb)}
}

func (_c *MockSender_Send_Call) Run(run func(ctx context.Context, chatID int64, text string, kb *tgbot.InlineKeyboardMarkup)) *MockSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *tgbot.InlineKeyboardMarkup
		if args[3] != nil {
			arg3 = args[3].(*tgbot.InlineKeyboardMarkup)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSender_Send_Call) Return(err error) *MockSender_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSender_Send_Call) RunAndReturn(run func(ctx context.Context, chatID int64, text string, kb *tgbot.InlineKeyboardMarkup) error) *MockSender_Send_Call {
	_c.Call.Return(run)
	return _c
}
